name: Send email new RSS Feed items	
on:
  rss:
    url: https://archlinux.org/feeds/news/
jobs:
  email:
    name: Post a email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: ${{ on.rss.outputs.content }}
          # Read file contents as body:
          to: 826284489@qq.com
          from: zhangzhoukai@outlook.com # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
